### ISSUE TITLE
COs should be able to see crew lists of other ships

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#47]
COs should be able to search the list of active ships and drill down to see lists of crewmembers.  This is for two reasons:

1.  In the event that a chapter hosts an event and somehow doesn't get a member's name, this allows the CO of the hosting chapter to look up the members of a chapter and possibly locate the member who attended their event.
2.  To facilitate getting members moved from the holding chapters to local chapters, COs should be able to view the list of crew in the holding chapters.  This list should show the member's name, home city, and state.

**Comment by dweinerATL** [comment]
BuPers and the Admiralty have decided that because of privacy concerns (i.e., a member with a restraining order), that CO's will only be able to see information on their own commands and any subordinate commands.  They will not be able to see other ships members.

Just don't go there, you'll loose with Steph and Martin :)
